#!/usr/bin/env bash
ROOT="$(dirname "$(readlink -f "$0")")"
source "${ROOT}/.venv/bin/activate"
# Add the build-kit directory to PYTHONPATH
export PYTHONPATH="${ROOT}:$PYTHONPATH"
python3.10 "${ROOT}/build-kit/scripts/cli.py" "$@"
